-- ProCast Platform Super Admin — migration 001 (PostgreSQL / Supabase ONLY)
-- Creates the platform-only tables. Safe to re-run (IF NOT EXISTS everywhere).
-- Applied by:  php platform-admin/migrate.php   (CLI only, production only)

CREATE TABLE IF NOT EXISTS platform_super_admins (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name       VARCHAR(120) NOT NULL,
    email           VARCHAR(190) NOT NULL,
    password_hash   VARCHAR(255) NOT NULL,                 -- Argon2id (bcrypt fallback)
    totp_secret     TEXT NULL,                             -- AES-256-GCM ciphertext, never plaintext
    totp_enrolled   SMALLINT NOT NULL DEFAULT 0,
    totp_last_step  BIGINT NOT NULL DEFAULT 0,             -- replay protection for TOTP codes
    status          VARCHAR(10) NOT NULL DEFAULT 'active',
    last_login_at   TIMESTAMPTZ NULL,
    last_login_ip   VARCHAR(64) NULL,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT platform_super_admins_status_chk CHECK (status IN ('active','inactive')),
    CONSTRAINT platform_super_admins_email_lower_chk CHECK (email = lower(email))
);
CREATE UNIQUE INDEX IF NOT EXISTS platform_super_admins_email_uq ON platform_super_admins (email);

-- Append-only audit trail ------------------------------------------------------
CREATE TABLE IF NOT EXISTS platform_audit_logs (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    super_admin_id   BIGINT NULL REFERENCES platform_super_admins(id) ON DELETE RESTRICT,  -- NULL only for pre-auth events
    action           VARCHAR(50) NOT NULL,
    target_store_id  INT NULL REFERENCES stores(id) ON DELETE RESTRICT,
    ip_address       VARCHAR(64) NOT NULL,
    user_agent       VARCHAR(255) NOT NULL DEFAULT '',
    details_json     JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS platform_audit_logs_created_idx ON platform_audit_logs (created_at DESC);
CREATE INDEX IF NOT EXISTS platform_audit_logs_store_idx   ON platform_audit_logs (target_store_id);
CREATE INDEX IF NOT EXISTS platform_audit_logs_admin_idx   ON platform_audit_logs (super_admin_id);

CREATE OR REPLACE FUNCTION platform_audit_logs_immutable() RETURNS trigger AS $$
BEGIN
    RAISE EXCEPTION 'platform_audit_logs is append-only (% not allowed)', TG_OP USING ERRCODE = 'insufficient_privilege';
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS platform_audit_logs_no_update ON platform_audit_logs;
CREATE TRIGGER platform_audit_logs_no_update
    BEFORE UPDATE OR DELETE ON platform_audit_logs
    FOR EACH ROW EXECUTE FUNCTION platform_audit_logs_immutable();

DROP TRIGGER IF EXISTS platform_audit_logs_no_truncate ON platform_audit_logs;
CREATE TRIGGER platform_audit_logs_no_truncate
    BEFORE TRUNCATE ON platform_audit_logs
    FOR EACH STATEMENT EXECUTE FUNCTION platform_audit_logs_immutable();

-- Brute-force protection ----------------------------------------------------------
CREATE TABLE IF NOT EXISTS platform_auth_attempts (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kind          VARCHAR(10) NOT NULL,          -- login | totp
    ip            VARCHAR(64) NOT NULL,
    identifier    VARCHAR(190) NOT NULL DEFAULT '',
    attempted_at  BIGINT NOT NULL                -- epoch seconds
);
CREATE INDEX IF NOT EXISTS platform_auth_attempts_ip_idx ON platform_auth_attempts (ip, attempted_at);
CREATE INDEX IF NOT EXISTS platform_auth_attempts_id_idx ON platform_auth_attempts (identifier, attempted_at);

CREATE TABLE IF NOT EXISTS platform_ip_bans (
    ip            VARCHAR(64) PRIMARY KEY,
    banned_until  BIGINT NOT NULL,               -- epoch seconds
    created_at    BIGINT NOT NULL
);
