-- ProCast Platform Super Admin — migration 003 (PostgreSQL ONLY)
-- Client-type tracking, admin-issued local-POS pairing codes, and the
-- hard-delete tombstone table.
--
-- Also backfills the two data gaps that made the Stores list unreadable:
--   * owner_name / owner_email were NULL for every store created before
--     migration 002, even though the real owner exists as users.role='owner'.
--   * stores.name was left as the literal 'ProCast' default from migration 001
--     while the actual store name lives in settings.shop_name.

-- Which client a store actually uses:
--   'web'   = the online POS in a browser
--   'app'   = installed PWA on a phone/tablet
--   'local' = an offline POS install that syncs through the cloud
ALTER TABLE stores ADD COLUMN IF NOT EXISTS client_type VARCHAR(10) NOT NULL DEFAULT 'web';

-- Recover the owner details from the users table (first owner per store).
UPDATE stores s
   SET owner_name  = COALESCE(NULLIF(s.owner_name, ''),  u.full_name),
       owner_email = COALESCE(NULLIF(s.owner_email, ''), u.email)
  FROM (
        SELECT DISTINCT ON (store_id) store_id, full_name, email
          FROM users
         WHERE role = 'owner'
         ORDER BY store_id, id
       ) u
 WHERE u.store_id = s.id
   AND (COALESCE(s.owner_name, '') = '' OR COALESCE(s.owner_email, '') = '');

-- Use the store's own shop_name when stores.name is still a placeholder.
UPDATE stores s
   SET name = COALESCE(NULLIF(t.value, ''), s.name)
  FROM settings t
 WHERE t.store_id = s.id
   AND t.key = 'shop_name'
   AND TRIM(COALESCE(t.value, '')) <> ''
   AND TRIM(COALESCE(s.name, '')) IN ('', 'ProCast', 'POS SYSTEM', 'PANGGA STORE', 'PANGGA POS');

-- Pairing codes an admin hands to a store so its OFFLINE POS install can
-- activate. Short-lived, single-use, never stored in plaintext.
CREATE TABLE IF NOT EXISTS platform_store_pairings (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_id     BIGINT NOT NULL REFERENCES stores(id) ON DELETE CASCADE,
    code_hash    VARCHAR(64) NOT NULL,          -- SHA-256 of the 6-digit code
    created_by   BIGINT NULL REFERENCES platform_super_admins(id) ON DELETE SET NULL,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    expires_at   TIMESTAMPTZ NOT NULL,          -- short TTL, see Env::pairingTtl()
    used_at      TIMESTAMPTZ NULL,              -- NULL until redeemed
    used_ip      VARCHAR(64) NULL
);
CREATE INDEX IF NOT EXISTS platform_store_pairings_store_idx ON platform_store_pairings (store_id);
CREATE INDEX IF NOT EXISTS platform_store_pairings_live_idx  ON platform_store_pairings (code_hash);

-- Hard deletes are irreversible, so keep the paper trail even though the
-- store row itself is removed.
CREATE TABLE IF NOT EXISTS platform_deleted_stores (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_id         BIGINT NOT NULL,
    store_name       VARCHAR(150) NOT NULL,
    owner_name       VARCHAR(120) NULL,
    owner_email      VARCHAR(190) NULL,
    user_count       INT NOT NULL DEFAULT 0,
    deleted_by       BIGINT NULL REFERENCES platform_super_admins(id) ON DELETE SET NULL,
    deleted_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    reason           TEXT NULL
);
CREATE INDEX IF NOT EXISTS platform_deleted_stores_store_idx ON platform_deleted_stores (store_id);

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'stores_client_type_chk') THEN
        ALTER TABLE stores ADD CONSTRAINT stores_client_type_chk
            CHECK (client_type IN ('web', 'app', 'local'));
    END IF;
END $$;

-- Allow hard-deleting a store that already has audit history -------------------
-- Without this, destroy() cannot work: platform_audit_logs.target_store_id is
-- ON DELETE RESTRICT and the table is append-only, so a store with even one
-- approval/suspension entry becomes undeletable. Both protections are real and
-- both are kept -- the audit row itself (action, ip, details, timestamp) is
-- preserved forever, we only drop the dangling pointer to a row that no longer
-- exists. platform_deleted_stores keeps the store name/owner for context.
CREATE OR REPLACE FUNCTION platform_audit_logs_immutable() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'UPDATE'
       AND NEW.id             IS NOT DISTINCT FROM OLD.id
       AND NEW.super_admin_id IS NOT DISTINCT FROM OLD.super_admin_id
       AND NEW.action         =  OLD.action
       AND NEW.ip_address     =  OLD.ip_address
       AND NEW.user_agent     =  OLD.user_agent
       AND NEW.details_json   =  OLD.details_json
       AND NEW.created_at     =  OLD.created_at
       AND OLD.target_store_id IS NOT NULL
       AND NEW.target_store_id IS NULL
    THEN
        RETURN NEW;   -- FK nulling after a store hard-delete; nothing else changed
    END IF;
    RAISE EXCEPTION 'platform_audit_logs is append-only (% not allowed)', TG_OP
        USING ERRCODE = 'insufficient_privilege';
END;
$$ LANGUAGE plpgsql;

ALTER TABLE platform_audit_logs DROP CONSTRAINT IF EXISTS platform_audit_logs_target_store_id_fkey;
ALTER TABLE platform_audit_logs
    ADD CONSTRAINT platform_audit_logs_target_store_id_fkey
    FOREIGN KEY (target_store_id) REFERENCES stores(id) ON DELETE SET NULL;

CREATE INDEX IF NOT EXISTS stores_client_type_idx ON stores (client_type);