-- ProCast Platform Super Admin — migration 004 (PostgreSQL ONLY)
-- Per-ACCOUNT activation codes for the local/offline POS.
--
-- Migration 003 issued one code per STORE, which unlocked the whole machine.
-- That is not sufficient: a cashier account created later ("Add user" in
-- Settings) would have been able to log in on an already-unlocked install
-- without ever proving anything. These codes are bound to a single users row
-- instead, so EVERY human account — the owner and each cashier/staff account —
-- needs its own code, and a brand-new account cannot use the local POS until
-- one is issued for it.
--
-- Redemption happens on the local install but is verified here, online, so a
-- code cannot be faked by editing the offline database. Short-lived,
-- single-use, never stored in plaintext.

CREATE TABLE IF NOT EXISTS platform_user_pairings (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    store_id     BIGINT NULL REFERENCES stores(id) ON DELETE CASCADE,
    code_hash    VARCHAR(64) NOT NULL,          -- SHA-256 of the 6-digit code
    created_by   BIGINT NULL REFERENCES platform_super_admins(id) ON DELETE SET NULL,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    expires_at   TIMESTAMPTZ NOT NULL,          -- short TTL, see PAIRING_CODE_TTL
    used_at      TIMESTAMPTZ NULL,              -- NULL until redeemed
    used_ip      VARCHAR(64) NULL
);
CREATE INDEX IF NOT EXISTS platform_user_pairings_user_idx  ON platform_user_pairings (user_id);
CREATE INDEX IF NOT EXISTS platform_user_pairings_hash_idx  ON platform_user_pairings (code_hash);
CREATE INDEX IF NOT EXISTS platform_user_pairings_store_idx ON platform_user_pairings (store_id);

-- At most ONE live (unused) code per account. Enforced by the database rather
-- than only in PHP so a double-click or a replayed POST can never mint two
-- valid codes for the same person. Retired codes keep used_at set, so this
-- partial index never blocks re-issuing after a code is spent.
CREATE UNIQUE INDEX IF NOT EXISTS platform_user_pairings_one_live
    ON platform_user_pairings (user_id)
    WHERE used_at IS NULL;