-- ProCast Platform Super Admin — migration 006 (PostgreSQL ONLY)
-- Two defects in the per-account pairing codes introduced by migration 004.
--
-- 1. NO UNIQUENESS ON THE CODE ITSELF.
--    004 guaranteed at most one live code per USER, but nothing stopped two
--    different people from being issued the SAME six digits. Six digits is a
--    1,000,000-value space and a busy store has several codes live at once, so
--    this is a birthday collision waiting to happen — and when it does it is
--    not merely confusing, it destroys a valid code:
--
--      cloud_pair_redeem runs one atomic
--        UPDATE ... WHERE code_hash = ? AND used_at IS NULL ...
--    Without uniqueness, a collision makes that single UPDATE match TWO rows.
--    Both are marked used, so redeeming Ben's code also silently burns Ana's,
--    and she is now locked out with no code of her own. RETURNING only yields
--    the first row, so the caller is never told anything went wrong.
--
--    The partial unique index below makes that state unreachable in the
--    database rather than merely unlikely in PHP. Minting retries on conflict,
--    so this costs nothing in the normal case.
--
-- 2. NO ROLE ON THE RECORD.
--    The code was minted from the account's CURRENT role but never recorded it.
--    Nothing therefore stopped a code issued to a cashier from still being
--    redeemable after that account was promoted, and the audit trail could not
--    say which role a code was minted for. Redemption now compares the
--    recorded role against the user's CURRENT role inside the same atomic
--    UPDATE, so a stale code is refused rather than silently granting the new,
--    higher role.
--
-- role is nullable: rows minted before this migration have no role recorded,
-- and NULL is treated as "do not check" so an existing unspent code still works
-- and is not stranded by an upgrade.

ALTER TABLE platform_user_pairings ADD COLUMN IF NOT EXISTS role VARCHAR(32) NULL;

COMMENT ON COLUMN platform_user_pairings.role IS
    'Role the code was minted for (owner/cashier/admin). NULL = minted before 006; redemption skips the role check for those.';

-- Backfill so existing live codes keep enforcing the role they were minted for
-- where we can still determine it. A NULL left here simply skips the check.
UPDATE platform_user_pairings p
   SET role = u.role
  FROM users u
 WHERE u.id = p.user_id AND p.role IS NULL;

-- At most one live (unused) code per DIGIT-SEQUENCE, across every account.
-- This is the real fix for defect 1 above: redemption's single UPDATE can no
-- longer match two rows, so one person's code can never burn another's.
-- Retired rows keep used_at set, so this never blocks re-issuing after a spend.
--
-- Existing databases may already contain a colliding pair of live codes; the
-- UPDATE retires the older of each pair first so this migration cannot fail on
-- its own data. Which code survives is arbitrary but harmless: both are dead
-- anyway once redeemed, and the owner can re-issue deliberately.
UPDATE platform_user_pairings older
   SET used_at = now(), code_cipher = NULL
  FROM platform_user_pairings newer
 WHERE older.code_hash  = newer.code_hash
   AND older.used_at IS NULL
   AND newer.used_at IS NULL
   AND older.id < newer.id;

CREATE UNIQUE INDEX IF NOT EXISTS platform_user_pairings_live_code_uniq
    ON platform_user_pairings (code_hash)
    WHERE used_at IS NULL;

-- 3. THROTTLE TABLE, PROPERLY MIGRATED.
--    cloud_pair_redeem has been creating this table at runtime inside the
--    request with CREATE TABLE IF NOT EXISTS. That works, but it means the
--    brute-force guard depends on a DDL statement executing on the hot path of
--    a PUBLIC, UNAUTHENTICATED endpoint. Under lock contention that DDL blocks
--    or fails, and the guard is the first thing to disappear.
--
--    Both endpoints now share this table, so it belongs in a migration like
--    everything else. The runtime CREATE TABLE IF NOT EXISTS is deliberately
--    left in place as a no-op safety net: an install that predates this
--    migration and never replays it must not lose its throttle.
--
--    ip_hash rather than a raw address: this table is a record of who tried to
--    guess access codes, and the same argument that keeps role out of the audit
--    log applies — the value is only ever compared for equality.
CREATE TABLE IF NOT EXISTS platform_pairing_attempts (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ip_hash    VARCHAR(64) NOT NULL,
    tried_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS platform_pairing_attempts_ip_idx
    ON platform_pairing_attempts (ip_hash, tried_at);
