-- ProCast Platform Super Admin — migration 007 (PostgreSQL ONLY)
--
-- Exists only to guarantee the cloud_pair_request throttle table on installs
-- where migration 006 is ALREADY RECORDED as applied.
--
-- 006 gained the platform_pairing_attempts DDL, but migrate.php skips any file
-- whose name is present in platform_migrations. An install that ran 006 before
-- that DDL was added to it will never replay the file, so the table would be
-- created solely by the runtime CREATE TABLE IF NOT EXISTS inside the request
-- handler. That is exactly the arrangement 006 was written to remove: the
-- brute-force guard for a PUBLIC, UNAUTHENTICATED endpoint would depend on DDL
-- executing on the hot path, which is the first thing to disappear under lock
-- contention.
--
-- Both statements are IF NOT EXISTS, so on a fresh install that already ran 006
-- with the DDL present this is a clean no-op and on an install that predates it
-- this does the real work. Running it twice is harmless.
--
-- ip_hash rather than a raw address: this table is a record of who tried to
-- guess access codes, and the same argument that keeps the role out of the audit
-- log applies — the value is only ever compared for equality, never displayed.

CREATE TABLE IF NOT EXISTS platform_pairing_attempts (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ip_hash    VARCHAR(64) NOT NULL,
    tried_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS platform_pairing_attempts_ip_idx
    ON platform_pairing_attempts (ip_hash, tried_at);
